#!/bin/bash

set -e

red="\033[0;31m"
nc="\033[0m"
green="\033[0;32m"
yellow="\033[1;33m"

front_dir="front"
back_dir="back"

if [ "$EUID" -ne 0 ]; then
    echo -e "${red}[ERROR] Please run as root${nc}"
    exit 1
fi

if [ ! -d "$front_dir" ]; then
    echo -e "${red}[ERROR] Frontend directory not found${nc}"
    exit 1
fi

if [ ! -d "$back_dir" ]; then
    echo -e "${red}[ERROR] Backend directory not found${nc}"
    exit 1
fi

echo -e "${yellow}Moving to frontend directory${nc}"
cd $front_dir

if command -v npm >/dev/null 2>&1; then
    echo -e "${green}[SUCCESS] Npm is correctly installed${nc}"
else
    echo -e "${red}[ERROR] Npm is not installed${nc}"
    exit 1
fi

echo -e "${yellow}Installing frontend dependencies${nc}"
npm install
echo -e "${green}[SUCCESS] Frontend dependencies installed${nc}"

echo -e "${yellow}Building frontend${nc}"
npm run build
echo -e "${green}[SUCCESS] Frontend built${nc}"

html_dir="/var/www/html/Jupido/"

if [ ! -d "$html_dir" ]; then
    echo -e "${red}[WARNING] Html directory not found${nc}"
    echo -e "${yellow}Creating html directory${nc}"
    mkdir -p $html_dir
    echo -e "${green}[SUCCESS] Html directory created${nc}"
else
    rm -rf $html_dir/*
fi

echo -e "${yellow}Moving frontend to html directory${nc}"
mv dist/* $html_dir
echo -e "${green}[SUCCESS] Frontend moved to html directory${nc}"

echo -e "${yellow}Deleting dist directory${nc}"
rm -rf dist
echo -e "${green}[SUCCESS] Dist directory deleted${nc}"

echo -e "${green}[SUCCESS] FRONTEND COMPLETLY BUILT${nc}"

echo -e "${yellow}Moving to backend directory${nc}"
cd ../$back_dir

echo -e "${yello}Moving backend directory to /etc/Jupido${nc}"
if [ ! -d "/etc/Jupido" ]; then
    echo -e "${red}[WARNING] Backend directory not found${nc}"
    echo -e "${yellow}Creating backend directory${nc}"
    mkdir -p '/etc/Jupido'
    echo -e "${green}[SUCCESS] Backend directory created${nc}"
else
    rm -rf "etc/Jupido/*"
    echo -e "${yellow}[WARNING] Backend directory cleared${nc}"
fi

cp -r * '/etc/Jupido'
echo -e "${green}[SUCCESS] Backend directory moved${nc}"
cd '/etc/Jupido'
echo -e "${yellow}Installing backend dependencies${nc}"

if command -v pip >/dev/null 2>&1; then
    echo -e "${green}[SUCCESS] Pip is correctly installed${nc}"
else
    echo -e "${red}[ERROR] Pip is not installed${nc}"
    exit 1
fi

pip install -r requirements.txt
echo -e "${green}[SUCCESS] Backend dependencies installed${nc}"

echo -e "${yellow}Running gunicorn server${nc}"
cd Jupido
if [ ! -d "config/gunicorn" ]; then
    echo -e "${red}[ERROR] Gunicorn config directory not found${nc}"
    exit 1
fi

echo -e "${yellow}[WARNING] Killing all gunicorn instances${nc}"
lines=$(ps ax | grep gunicorn | wc -l)
if [ $lines -ne 1 ]; then
  pkill -f gunicorn
  echo -e "${green}[SUCCESS] Gunicorn instances killed${nc}"
else
  echo -e "${yellow}[WARNING] No gunicorn instances found${nc}"
fi

log_dir="/var/log/gunicorn"
run_dir="/var/run/gunicorn"

if [ ! -d "$log_dir" ]; then
    echo -e "${red}[WARNING] Log directory not found${nc}"
    echo -e "${yellow}Creating log directory${nc}"
    mkdir -p $log_dir
    echo -e "${green}[SUCCESS] Log directory created${nc}"
else
    rm -rf $log_dir/*
fi

if [ ! -d "$run_dir" ]; then
    echo -e "${red}[WARNING] Run directory not found${nc}"
    echo -e "${yellow}Creating run directory${nc}"
    mkdir -p $run_dir
    echo -e "${green}[SUCCESS] Run directory created${nc}"
else
    rm -rf $run_dir/*
fi

gunicorn -c config/gunicorn/prod.py

echo -e "${green}[SUCCESS] BACKEND COMPLETLY BUILT${nc}"

echo -e "${green}[SUCCESS] APP COMPLETLY BUILT${nc}"